export const bars = <i className="fa-solid fa-bars" />;
export const arrowLeft = <i className="fa-solid fa-arrow-left" />;
export const add = <i className="fa-solid fa-plus" />;
export const moon = <i className="fa-solid fa-moon" />;
export const search = <i className="fa-solid fa-magnifying-glass" />;
export const bell = <i className="fa-solid fa-bell" />;
export const home = <i className="fa-solid fa-house" />;
export const list = <i className="fa-solid fa-list-check" />;
export const check = <i className="fa-solid fa-check" />;
export const help = <i className="fa-solid fa-circle-info" />;
export const gear = <i className="fa-solid fa-gear" />;
export const login = <i className="fa-solid fa-right-to-bracket" />;
export const logout = <i className="fa-solid fa-right-from-bracket" />;
export const user = <i className="fa-solid fa-user" />;
export const join = <i className="fa-solid fa-user-plus" />;
export const heart = <i className="fa-solid fa-heart" />;
export const edit = <i className="fa-solid fa-file-pen" />;
export const users = <i className="fa-solid fa-user-group" />;
export const todo = <i className="fa-solid fa-clipboard-list" />;
export const down = <i className="fa-solid fa-caret-down" />;
export const trash = <i className="fa-solid fa-trash" />;
export const admin = <i className="fa-solid fa-lock" />;
export const linked = <i className="fa-brands fa-linkedin" />;
export const mailIcon = <i className="fa-solid fa-envelope" />;
export const plus = <i className="fa-solid fa-plus fa-beat-fade" />;
export const save = <i class="fa-regular fa-floppy-disk"></i>;
